---
# handlers file for prometheus-node

- name: reload systemd
  become: true
  command: systemctl daemon-reload
  tags:
    # [ANSIBLE0006] systemctl used in place of systemd module
    - skip_ansible_lint

- name: restart prometheus-node-exporter
  become: true
  service:
    name: prometheus-node-exporter
    state: restarted
